events {}

http {
  server {
    listen 80;
    server_name _;

    location / {
      proxy_pass http://nest_backend:3001;
    }

    location /api/executions/exec-block {
      proxy_pass http://nest_backend:3001;
      proxy_buffering off;
    }
  }
}